### ISSUE TITLE
Cannot find module when use module with typings in package.json #81

### ISSUE THREAD

**Issue by squarepants** [s-panferov/awesome-typescript-loader#82] opened 2015-11-25 07:33 UTC
@s-panferov  seems like I can't re-open that issue #81 .

 I did what you said and got that error again. 

![image](https://cloud.githubusercontent.com/assets/2764458/11390967/bcb5b826-9389-11e5-955a-c77ab83ee3c2.png)

Still don't know how to solve this problem.

The test code is on https://github.com/squarepants/tstest.git

clone it , npm i and run webpack

**Comment by s-panferov** [comment] 2015-11-25 07:41
@squarepants it seems that TypeScript behaves correctly, because it doesn't know a shape of 'cyra' and there is no `.d.ts` file in https://github.com/kabsky/cyra.

If you want to use some external library that doesn't have any `.d.ts` file, you have several options:

1) Write `.d.ts` file by yourself. The easiest way to do this is to write a stub of `cyra.d.ts`:

```
declare module 'cyra' {
	var cyra: any;
	exports = cyra;	
}
```

2) Use plain `require`: `let cyra = require('cyra');`. TypeScript will not type check such imports and `cyra` will be of `any` type.

**Comment by squarepants** [comment] 2015-11-25 09:49
Sorry that .d.ts file was push after your comment , It does exist in the npm modules before and heres that .d.ts file 
```
export interface PageTransitionObject {
   fromPageDisappear(next: Function): void;
   toPageAppear(next: Function): void;
}
export interface AppInitObject {
   root: string;
   default: string;
   pageTransition?: PageTransitionObject;
}
export interface PageDefineObject {
   id: string;
   initialize?(next: Function, ...args): void;
   willAppear?(next: Function, ...args): void;
   didAppear?(next: Function, ...args): void;
   willDisappear?(next: Function, ...args): void;
   defineActions?(): void;
   prepareForAction?(action: Action, destinationPagePerform: (functionName: string, ...args) => void): void;
}
export class Page {
   public container: Element;
   public context: any;
   public transferData: any;
   public performAction(action: Action, data?: any, isBack?: boolean);
}
export class Action {
   public fromPageID: string;
   public toPageID: string;
}
export class Route {
   public path: string;
   public page: Page;
}


export var context: any;
export function initApp(appInitObject: AppInitObject): void;
export function definePage(pageDefineObject: PageDefineObject): Page;
export function defineRoute(path: string, page: Page): Route;
export function defineAction(fromPageID: string, toPageID: string): Action;
```

**Comment by squarepants** [comment] 2015-12-01 08:55
We have found this problem
in awesome-typescript-loader/src/index.ts
```
/// <reference path='../node_modules/typescript/lib/typescriptServices.d.ts' />
```
this path does not exists, when we replace this with our own typescript module in project, All problems gone away.

**Comment by tlancina** [comment] 2015-12-01 20:15
Have the same issue, here's a repo reproducing: https://github.com/tlancina/awesome-ts-loader-issue.
`npm install` and then `webpack` will error.

Hopefully not a configuration error on my part! Digging into it a little, https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L77 `host.fileExists(fileName)` always returns false, even though the file does exist.  I'm not sure how it should be added to the compiler context, since dependencies seem to only be added for `imports` and not `exports`.

These are the exports that fail: https://github.com/angular/angular/blob/master/modules/angular2/angular2.ts#L1-L7

Using awesome-typescript-loader 0.15.4 and typescript 1.7.3.

Let me know if I can provide anything else!

**Comment by s-panferov** [comment] 2015-12-02 07:13
This is an error in the loader. I think that it might be fixed in v0.15.5, please try it.

**Comment by s-panferov** [comment] 2015-12-02 07:36
There is one more bugfix in v0.15.6

**Comment by tlancina** [comment] 2015-12-02 17:29
@s-panferov big thanks for the timely fix!

**Closed** 2016-03-20 07:00 UTC
