### ISSUE TITLE
[3.0.0-beta.17] Generated declaration with lowercase path of types reference

### ISSUE THREAD

**Issue by morlay** [s-panferov/awesome-typescript-loader#326] opened 2016-12-16 01:24 UTC
```
/// <reference types="typescript/lib/typescriptservices" />
```
![image](https://cloud.githubusercontent.com/assets/1667873/21248325/3ed31f2a-c371-11e6-8bff-4f8cbf1c6cbf.png)

**Comment by TheElf** [comment] 2016-12-22 01:18
Looks like this may habe been caused by:
Microsoft/TypeScript#10340

As of that merge, all reference tags are used as lowercase'd

**Comment by s-panferov** [comment] 2017-02-05 13:05
Fixed in the latest version

**Closed by s-panferov** 2017-02-05 13:05 UTC
