### ISSUE TITLE
TypeError: Cannot read property '_tsInstances' of undefined

### ISSUE THREAD

**Issue by iHaiduk** [s-panferov/awesome-typescript-loader#541] opened 2018-02-26 21:36 UTC
I have error with new version webpack.
```
~/node_modules/awesome-typescript-loader/src/instance.ts:73
if (!compiler) {
^
    TypeError: Cannot read property '_tsInstances' of undefined
    at resolveInstance (~/node_modules/awesome-typescript-loader/src/instance.ts:73:20)
    at ~/node_modules/awesome-typescript-loader/src/instance.ts:366:26
    at AsyncSeriesHook.eval [as callAsync] (eval at create (~/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:16:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (~/node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at Watching._go (~/node_modules/webpack/lib/Watching.js:40:32)
    at Watching._invalidate (~/node_modules/webpack/lib/Watching.js:164:9)
    at watcher.compiler.watchFileSystem.watch (~/node_modules/webpack/lib/Watching.js:135:10)
    at Watchpack.watcher.once (~/node_modules/webpack/lib/node/NodeWatchFileSystem.js:43:4)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Watchpack.emit (events.js:214:7)
    at Watchpack._onTimeout (~/node_modules/watchpack/lib/watchpack.js:142:7)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```
## package.json
```
{
  "scripts": {
    "build:dev": "./node_modules/.bin/webpack --colors --config ./webpack.config.js --mode development",
    "build:prod": "./node_modules/.bin/webpack --colors --config ./webpack.config.js",
    "run:dev": "./node_modules/.bin/nodemon ./dist/index.js",
    "lint-typescript": "./node_modules/.bin/tslint ./src/**/* -c tslint.json",
    "lint-typescript-fix": "./node_modules/.bin/tslint ./src/**/* -c tslint.json --fix"
  },
  "devDependencies": {
    "@types/axios": "0.14.0",
    "@types/node": "9.4.6",
    "@types/pino": "4.7.1",
    "awesome-typescript-loader": "3.5.0",
    "babel-loader": "7.1.3",
    "babel-plugin-closure-elimination": "1.3.0",
    "babel-plugin-loop-optimizer": "1.4.1",
    "babel-preset-env": "1.6.1",
    "babel-preset-stage-0": "6.24.1",
    "nodemon": "1.15.1",
    "source-map-loader": "0.2.3",
    "ts-loader": "4.0.0",
    "tslint": "5.9.1",
    "typescript": "2.7.2",
    "webpack": "4.0.1",
    "webpack-bundle-analyzer": "2.11.0",
    "webpack-cli": "2.0.9",
    "webpack-error-notification": "0.1.7",
    "webpack-node-externals": "1.6.0"
  },
  "dependencies": {
    "@types/mongoose": "5.0.3",
    "axios": "0.18.0",
    "cheerio": "1.0.0-rc.2",
    "fast-html-parser": "1.0.1",
    "html-parser": "0.11.0",
    "mongoose": "5.0.7",
    "node-cmd": "3.0.0",
    "pino": "4.13.0",
    "query-hash": "2.0.1"
  }
}
```
## tsconfig.json
```
{
  "compilerOptions": {
    "target": "es2017",
    "outDir": "dist",
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "inlineSources": true,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "types": ["node"],
    "typeRoots": ["./node_modules/@types"],
    "baseUrl": ".",
    "paths": {
      "_config":            [ "./src/config.ts" ],
      "_interfaces":        [ "./src/interfaces.ts" ],
      "_controller/*":      [ "./src/controllers/*" ],
      "_model/*":           [ "./src/models/*" ],
      "_utils/*":           [ "./src/utils/*" ]
    }
  },
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true,
    "useCache": true,
    "cacheDirectory": ".gulp/ts",
    "useTranspileModule": true,
    "silent": true,
    "useBabel": true,
    "babelOptions": {
      "presets": ["stage-0", ["env", { "targets": { "node": "current" } }]],
      "plugins": ["closure-elimination", "loop-optimizer"]
    }
  },
  "exclude": [
    ".gulp",
    "node_modules",
    "server",
    "dist"
  ],

  "include": [
    "./src/**/*"
  ],
  "compileOnSave": false,
  "buildOnSave": false
}
```
## webpack.config.js
```
const nodeExternals = require('webpack-node-externals');
const {resolve} = require('path');
const webpack = require('webpack');
const WebpackErrorNotificationPlugin = require('webpack-error-notification');
const {BundleAnalyzerPlugin} = require('webpack-bundle-analyzer');


module.exports = {

    target: "node",

    entry: {
        index: resolve(__dirname, 'src', 'index.ts'),
    },

    // Currently we need to add '.ts' to the resolve.extensions array.
    resolve: {
        modules: ['node_modules'],
        extensions: ['.tsx', '.ts', '.js'],
        descriptionFiles: ['package.json'],
        alias: {
            "_config": resolve(__dirname, 'src', 'config.ts'),
            "_interfaces": resolve(__dirname, 'src', 'interfaces.ts'),
            "_controller": resolve(__dirname, 'src', 'controllers'),
            "_model": resolve(__dirname, 'src', 'models'),
            "_utils": resolve(__dirname, 'src', 'utils'),
        },
    },

    output: {
        path: resolve(__dirname, 'dist'),
        filename: '[name].js',
        chunkFilename: '[name]-[id].js',
        libraryTarget: 'commonjs2'
    },

    // Source maps support ('inline-source-map' also works)
    devtool: 'inline-source-map',
    externals: [nodeExternals()],

    stats: {
        colors: true,
        modules: true,
        reasons: true,
        errorDetails: true
    },

    node: {
        console: false,
        global: true,
        process: true,
        Buffer: true,
        __filename: true,
        __dirname: true,
        setImmediate: true
    },

    // Add the loader for .ts files.
    module: {
        rules: [
            {
                enforce: 'pre',
                test: /\.ts(x?)$/,
                use: "source-map-loader",
                exclude: /node_modules/,
            },
            {
                test: /\.ts(x?)$/,
                use: [
                    {loader: 'awesome-typescript-loader'}
                ],
                include: [
                    resolve(__dirname, 'src')
                ],
                exclude: /node_modules/,
            }
        ]
    },
    plugins: [
        new webpack.NoEmitOnErrorsPlugin(),
        new webpack.NamedModulesPlugin(),
        new WebpackErrorNotificationPlugin(),
        // new CheckerPlugin(),

        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify('development')
            }
        }),

        new BundleAnalyzerPlugin({
            openAnalyzer: false,
        }),
    ],

    watch: true,
};
```

**Comment by s-panferov** [comment] 2018-02-27 00:53
webpack4?

**Comment by darklightcode** [comment] 2018-02-27 07:35
I get ` if (!compiler._tsInstances)` , yet it's on the same line as iHaiduk's log. 
When i start the server everything goes ok, no errors, but when i change even a string and recompiling starts, the app crashes with the error below, i'm using:

Webpack 4.0.1 + webpack-dev-middleware
npm v5.6.0
node v8.9.3

```
~\node_modules/awesome-typescript-loader/src/instance.ts:73
     if (!compiler._tsInstances) {
                   ^
    TypeError: Cannot read property '_tsInstances' of undefined
        at resolveInstance (~/node_modules/awesome-typescript-loader/src/instance.ts:73:20)
        at ~/node_modules/awesome-typescript-loader/src/instance.ts:366:26
    at _err1 (eval at create (~/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:21:1)
    at invalid (~/node_modules/webpack-dev-middleware/lib/context.js:76:7)
    at context.compiler.plugin (~/node_modules/webpack-dev-middleware/lib/context.js:116:5)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (~/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:16:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (~/node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at Watching._go (~/node_modules/webpack/lib/Watching.js:40:32)
    at Watching._invalidate (~/node_modules/webpack/lib/Watching.js:164:9)
    at watcher.compiler.watchFileSystem.watch (~/node_modules/webpack/lib/Watching.js:135:10)
    at Watchpack.watcher.once (~/node_modules/webpack/lib/node/NodeWatchFileSystem.js:43:4)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Watchpack.emit (events.js:214:7)
    at Watchpack._onTimeout (~/node_modules/watchpack/lib/watchpack.js:142:7)
    at ontimeout (timers.js:475:11)
```

**Comment by xingyun909** [comment] 2018-02-27 08:40
you can use ts-loader

**Comment by amitdahan** [comment] 2018-02-27 09:17
Happens to me as well, only on incremental builds. Webpack 4.0.1, at-loader 4.0.0-0.
seems like `compiler` is undefined in the `resolveInstance` function, whatever that means :)

**Comment by s-panferov** [comment] 2018-02-27 17:18
Duplicate of #534

**Closed by s-panferov** 2018-02-27 17:18 UTC

**Comment by kmvan** [comment] 2018-03-19 03:08
same problem on Webpack4.1.1

**Comment by QuantumInformation** [comment] 2018-03-22 10:23
Having this issue, causing caching of old postcss files

**Comment by alveshelio** [comment] 2018-03-26 01:42
I'm having the same issue, whenever I save a file and it tries to recompile I get this error. I'm using Webpack 4 and awesome-typescript-loader 4.0.1.
Any idea what could be the problem?

**Comment by kuldeepkeshwar** [comment] 2018-04-23 18:08
@alveshelio I'm also facing same issue, have you got it working ?

**Comment by zhujun24** [comment] 2018-12-05 12:22
`awesome-typescript-loader@5.0.0-1` work well
